### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [Solarex/solarex.github.com#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`atom.xml`](https://github.com/Solarex/solarex.github.com/blob/0455ddefeca009cac900afb8716316f537732979/blog/categories/tools/atom.xml). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by flyfire** [comment]
url replaced already,thanks for keeping me updated.
